const C=window.JARVIS_CONFIG||{};
const BASE=(C.SUPABASE_URL||"").replace(/\/$/,""),KEY=C.SUPABASE_PUBLISHABLE_KEY||"",GATEWAY=C.ASH_GATEWAY_URL||"/api/ash";
let session=JSON.parse(localStorage.getItem("ash-session")||"null"),profile={assistant_name:"Ash",personality_preset:"adaptive",preferred_mode:"medium",wake_word:"Ash",custom_instructions:"",behavior_config:{verbosity:"balanced",proactivity:"balanced",humor:20},voice_config:{auto_speak:true,voice_id:"cjVigY5qzO86Huf0OWal"}},mode=localStorage.getItem("ash-mode")||"medium",tab="home",messages=[];

const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const headers=()=>({apikey:KEY,"Content-Type":"application/json",...(session?.access_token?{Authorization:"Bearer "+session.access_token}:{})});
async function supa(path,opt={}){const r=await fetch(BASE+path,{...opt,headers:{...headers(),...(opt.headers||{})}});let d={};try{d=await r.json()}catch{};if(!r.ok)throw new Error(d?.msg||d?.message||d?.error_description||d?.error||("HTTP "+r.status));return d}
function save(s){session={access_token:s.access_token,refresh_token:s.refresh_token,user:s.user};localStorage.setItem("ash-session",JSON.stringify(session))}
async function login(email,password){save(await supa("/auth/v1/token?grant_type=password",{method:"POST",body:JSON.stringify({email,password})}))}
async function signup(email,password,name){const d=await supa("/auth/v1/signup",{method:"POST",body:JSON.stringify({email,password,data:{full_name:name}})});if(d.access_token)save(d);return d}
async function loadProfile(){if(!session)return;try{const r=await supa("/rest/v1/jarvis_profiles?user_id=eq."+encodeURIComponent(session.user.id)+"&select=*");if(r?.[0])profile={...profile,...r[0],behavior_config:{...profile.behavior_config,...(r[0].behavior_config||{})},voice_config:{...profile.voice_config,...(r[0].voice_config||{})}};mode=profile.preferred_mode||mode}catch{}}
async function saveProfile(){const body={assistant_name:document.querySelector("#assistantName").value.trim()||"Ash",wake_word:document.querySelector("#wakeWord").value.trim()||"Ash",personality_preset:document.querySelector("#personality").value,preferred_mode:mode,custom_instructions:document.querySelector("#instructions").value.trim(),behavior_config:{...profile.behavior_config,verbosity:document.querySelector("#verbosity").value,proactivity:document.querySelector("#proactivity").value,humor:Number(document.querySelector("#humor").value)},voice_config:{...profile.voice_config,auto_speak:document.querySelector("#speak").checked,voice_id:document.querySelector("#voice").value}};const r=await supa("/rest/v1/jarvis_profiles?user_id=eq."+encodeURIComponent(session.user.id),{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(body)});profile={...profile,...(r?.[0]||body)};render();toast("Saved")}
function toast(t){const n=document.createElement("div");n.className="toast";n.textContent=t;document.body.append(n);setTimeout(()=>n.remove(),2200)}
function shell(content){return `<main class="app"><header><div class="brand"><div class="core">A</div><div><b>${esc(profile.assistant_name)}</b><span>PERSONAL AI ORGANIZATION</span></div></div><div class="status">● ONLINE</div></header>${content}</main>${session?`<nav><button data-tab="home">⌂<small>Home</small></button><button data-tab="team">◇<small>Team</small></button><button data-tab="settings">⚙<small>You</small></button></nav>`:""}`}
function authView(){return shell(`<section class="center"><div class="heroCore">A</div><p class="eyebrow">ASH · PERSONAL INTELLIGENCE SYSTEM</p><h1>One assistant.<br>An organization behind it.</h1><p class="muted">Sign in to sync Ash across web, phone and desktop.</p><div class="card auth"><input id="email" type="email" placeholder="Email"><input id="password" type="password" placeholder="Password"><input id="name" placeholder="Name for new account"><div class="row"><button id="signin" class="primary">Sign in</button><button id="signup">Create account</button></div><p id="authMsg" class="muted"></p></div></section>`)}
function home(){return shell(`<section class="hero card"><div><p class="eyebrow">READY</p><h1>${esc(profile.assistant_name)}, online.</h1><p>Ask naturally. Ash routes the work internally and returns one answer.</p></div><div class="heroCore small">A</div></section><section class="modes">${["instant","medium","high"].map(x=>`<button data-mode="${x}" class="${mode===x?"active":""}">${x}</button>`).join("")}</section><section class="feed">${messages.length?messages.slice(-12).map(m=>`<article class="${m.role==="user"?"mine":"ash"}"><small>${m.role==="user"?"YOU":esc(profile.assistant_name).toUpperCase()}</small><p>${esc(m.content)}</p></article>`).join(""):`<article class="ash"><small>${esc(profile.assistant_name).toUpperCase()}</small><p>What are we building, solving or getting done?</p></article>`}</section><section class="composer card"><button id="mic" class="mic">◉</button><textarea id="prompt" placeholder="Talk to ${esc(profile.assistant_name)}…"></textarea><button id="send" class="primary">↗</button></section>`)}
function team(){const names=["Chief Orchestrator","Project Manager","Business Analyst","Research Analyst","Software Architect","Frontend Engineer","Backend Engineer","Desktop Engineer","Mobile Engineer","AI Engineer","Security Engineer","QA Engineer","Bug Fixer","UI Designer","UX Designer","Communications"];return shell(`<section class="page"><p class="eyebrow">ORGANIZATION</p><h1>Specialists behind Ash</h1><div class="grid">${names.map((n,i)=>`<div class="card agent"><span>${String(i+1).padStart(2,"0")}</span><b>${n}</b></div>`).join("")}</div></section>`)}
function settings(){return shell(`<section class="page"><p class="eyebrow">PERSONALIZE</p><h1>Make Ash yours</h1><div class="card settings"><label>Assistant name<input id="assistantName" value="${esc(profile.assistant_name)}"></label><label>Wake word<input id="wakeWord" value="${esc(profile.wake_word)}"></label><div class="two"><label>Personality<select id="personality">${["adaptive","executive","companion","builder","analyst","coach"].map(x=>`<option ${profile.personality_preset===x?"selected":""}>${x}</option>`).join("")}</select></label><label>Verbosity<select id="verbosity">${["concise","balanced","detailed"].map(x=>`<option ${profile.behavior_config?.verbosity===x?"selected":""}>${x}</option>`).join("")}</select></label></div><div class="two"><label>Proactivity<select id="proactivity">${["quiet","balanced","proactive"].map(x=>`<option ${profile.behavior_config?.proactivity===x?"selected":""}>${x}</option>`).join("")}</select></label><label>Humor<input id="humor" type="range" min="0" max="100" value="${Number(profile.behavior_config?.humor??20)}"></label></div><label>Voice<select id="voice"><option value="cjVigY5qzO86Huf0OWal">Eric · smooth</option><option value="EXAVITQu4vr4xnSDxMaL">Sarah · confident</option></select></label><label class="check"><input id="speak" type="checkbox" ${profile.voice_config?.auto_speak!==false?"checked":""}> Speak responses</label><label>Custom instructions<textarea id="instructions" rows="4">${esc(profile.custom_instructions||"")}</textarea></label><button id="save" class="primary">Save personalization</button></div><div class="card about"><b>About Ash</b><p>Developed by Jake Harvey. Ash is customizable, evidence-aware and user-controlled.</p></div><button id="signout">Sign out</button></section>`)}
function render(){document.querySelector("#app").innerHTML=session?(tab==="home"?home():tab==="team"?team():settings()):authView();bind()}
function bind(){document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;localStorage.setItem("ash-mode",mode);render()});document.querySelector("#signin")?.addEventListener("click",async()=>{const m=document.querySelector("#authMsg");m.textContent="Connecting…";try{await login(email.value,password.value);await loadProfile();render()}catch(e){m.textContent=e.message}});document.querySelector("#signup")?.addEventListener("click",async()=>{const m=document.querySelector("#authMsg");m.textContent="Creating…";try{const d=await signup(email.value,password.value,name.value);m.textContent=d.access_token?"Connected.":"Account created. Check your email if confirmation is enabled.";if(session){await loadProfile();render()}}catch(e){m.textContent=e.message}});document.querySelector("#send")?.addEventListener("click",send);document.querySelector("#prompt")?.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}});document.querySelector("#mic")?.addEventListener("click",listen);document.querySelector("#save")?.addEventListener("click",saveProfile);document.querySelector("#signout")?.addEventListener("click",()=>{session=null;localStorage.removeItem("ash-session");render()})}
async function send(){const box=document.querySelector("#prompt"),message=box?.value.trim();if(!message)return;box.value="";messages.push({role:"user",content:message});render();try{const r=await fetch(GATEWAY,{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+session.access_token},body:JSON.stringify({action:"chat",message,mode,history:messages.slice(-10,-1)})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Ash is unavailable.");messages.push({role:"assistant",content:d.answer||"Done."});render();speak(d.answer)}catch(e){messages.push({role:"assistant",content:e.message});render()}}
function listen(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast("Voice input needs a supported browser.");return}const r=new SR();r.lang=navigator.language||"en-US";r.onresult=e=>{document.querySelector("#prompt").value=e.results[0][0].transcript;send()};r.onerror=()=>toast("I couldn't hear that clearly.");r.start()}
async function speak(text){if(!text||profile.voice_config?.auto_speak===false)return;try{const r=await fetch(GATEWAY,{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+session.access_token},body:JSON.stringify({action:"speech",text:text.slice(0,5000),voice_id:profile.voice_config?.voice_id})});if(r.ok&&r.headers.get("content-type")?.includes("audio")){new Audio(URL.createObjectURL(await r.blob())).play();return}}catch{}if("speechSynthesis"in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(text.slice(0,1600)))}}
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("/sw.js").catch(()=>{}));
if(session)await loadProfile();render();